[package]
name = "mollie-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
lsp-types = { version = "0.11.0", package = "gen-lsp-types", features = ["url"] }
lsp-server = "0.10.0"
serde_json = "1"
mollie-index.workspace = true
mollie-lexer.workspace = true
mollie-shared.workspace = true
mollie-typed-ast.workspace = true
mollie-typing.workspace = true

[lints]
workspace = true
